Feat/homepage
desoindx/hub-collectivites pull request #1
Opened 2024-08-14 18:14 UTC by rtaieb

2024-08-15 07:09 UTC, desoindx requested changes

2024-08-15 07:09 UTC, desoindx commented on public/images/home/logo-anct.png
Pq l'image est la deux fois ?

2024-08-15 07:09 UTC, desoindx commented on public/images/home/logo-mte.png
pareil ?

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.module.css
> +    padding-top: 3rem;
il y a 4 espaces sur le tab, c'est possible de passer à 2 ?

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.module.css
> +.sectionTitle {
a supprimer

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.module.css
> +}
Manque un EOF

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +    return <div>
Div inutile, utiliser un fragment

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                <h1 className={styles.mainTitle}>{"La plateforme d'accompagnement sur mesure pour vos projets"}</h1>
```suggestion
                <h1 className={styles.mainTitle}>La plateforme d'accompagnement sur mesure pour vos projets</h1>
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                    className="fr-text--lead">{"Accélérer vos projets du quotidien en les orientant le plus en amont possible vers le bon service d'accompagnement"}
```suggestion
                    className="fr-text--lead">Accélérer vos projets du quotidien en les orientant le plus en amont possible vers le bon service d'accompagnement
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +        <div className={classNames(styles.section)}>
```suggestion
        <div className={styles.section}>
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                <h2 className={classNames("fr-h2")}>{"Un service intégré à l'écosystème"}</h2>
Pas sur qu'il y ait besoin de mettre la class fr-h2 sur un h2 ?
```suggestion
                <h2 className="fr-h2">Un service intégré à l'écosystème</h2>
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                                       alt="Logo du ministère de la transition Ecologique"
pas sur que les alt soit utile, on a des images comme ca sans context, ca me parait plus decoratif qu'autre chose

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                <h2 className={classNames("fr-h2")}>{"Simple et concret pour les collectivités"}</h2>
```suggestion
                <h2 className="fr-h2">Simple et concret pour les collectivités</h2>
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.module.css
> +}
peut etre merger ?

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.module.css
> +    flex-direction: row;
inutile, valeur par defaut

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.module.css
> +    flex-direction: row;
inutile, valeur par defaut

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                <h2 className={classNames("fr-h2")}>{"Une question, un avis ? Contactez-nous"}</h2>
```suggestion
                <h2 className="fr-h2">Une question, un avis ? Contactez-nous</h2>
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                    {"Si vous souhaitez contacter l’équipe pour une question, un problème ou simplement donnez votre " +
```suggestion
                    Si vous souhaitez contacter l’équipe pour une question, un problème ou simplement donnez votre
```

2024-08-15 07:09 UTC, desoindx commented on src/app/(home)/page.tsx
> +                        "avis dans le but d’améliorer le service, n’hésitez pas à nous écrire via le formulaire ci-dessous."}
```suggestion
                        avis dans le but d’améliorer le service, n’hésitez pas à nous écrire via le formulaire ci-dessous.
```

2024-08-15 07:11 UTC, desoindx reviewed
Le résultat n'est pas responsive

2024-08-16 06:59 UTC, rtaieb commented on public/images/home/logo-anct.png
c'est une erreur, je supprime celle ci.

2024-08-16 06:59 UTC, rtaieb commented on public/images/home/logo-mte.png
idem

2024-08-16 06:59 UTC, rtaieb commented on src/app/(home)/page.module.css
> +    padding-top: 3rem;
yes

2024-08-16 07:06 UTC, rtaieb commented on src/app/(home)/page.tsx
> +                <h2 className={classNames("fr-h2")}>{"Un service intégré à l'écosystème"}</h2>
Si je l'enlève, le titre sera en bleu du fait du fichier globals.css.
Si on peut retirer ce qu'il y a dans le globals.css pour les hx, alors cette classe sera effectivement inutile.

2024-08-16 07:07 UTC, rtaieb commented on src/app/(home)/page.tsx
> +                                       alt="Logo du ministère de la transition Ecologique"
Je trouve que si on a pas les images, on ne comprend pas de quel écosystème on parle dans le titre, donc pour moi il y avait une valeur informative de ces images, mais si tu veux je supprime les alt.

2024-08-16 08:02 UTC, desoindx approved these changes

2024-08-16 08:25 UTC, merged